-- 1. 个人信息表
CREATE TABLE profile (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    avatar VARCHAR(255) NOT NULL COMMENT '头像图片路径',
    name VARCHAR(100) NOT NULL COMMENT '姓名或昵称',
    bio TEXT NOT NULL COMMENT '个人简介',
    github_url VARCHAR(255) DEFAULT NULL COMMENT 'GitHub链接',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='个人主页基本信息表';


-- 2. 项目表
CREATE TABLE projects (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(150) NOT NULL COMMENT '项目标题',
    description TEXT NOT NULL COMMENT '项目简介',
    image VARCHAR(255) DEFAULT NULL COMMENT '项目图片路径',
    project_url VARCHAR(255) DEFAULT NULL COMMENT '项目跳转链接',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '排序，数字越小越靠前',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目列表表';


-- 3. 管理日志表
CREATE TABLE admin_logs (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    action_type VARCHAR(50) NOT NULL COMMENT '操作类型，如 login/add/edit/delete',
    target_table VARCHAR(50) DEFAULT NULL COMMENT '操作的表名',
    target_id INT DEFAULT NULL COMMENT '操作记录的ID',
    action_detail TEXT DEFAULT NULL COMMENT '操作详情',
    ip_address VARCHAR(45) DEFAULT NULL COMMENT '操作者IP',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='后台操作日志表';